name: automated deployment of an mkdocs project

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip3 install mkdocs-material
        # - run: mkdocs build -c -t material
      - run: mkdocs gh-deploy -c -t material --force
